Connect to drive

In [1]:
from google.colab import drive
drive.mount('/root/gdrive', force_remount=True)

Mounted at /root/gdrive


In [2]:
%cd /root/gdrive/MyDrive/Potrika

/root/gdrive/MyDrive/Potrika


In [3]:
!ls

make_data.py		  potrika_20000_old.gsheet  potrika_20000_v4.csv
potrika_20000.csv.gsheet  potrika_20000_v2.csv	    potrika_20000_v5.csv
potrika_20000_old.csv	  potrika_20000_v3.csv	    potrika_30000.csv


Import libraries

In [4]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [5]:
p = 5
if(p %2 == 0):
  print('even')
else:
  print('odd')

odd


Load data

In [6]:
import csv
data = []
with open('potrika_20000_v5.csv', encoding='utf-8') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
      data.append(row)
print(data[0])

['সাভারের কবিরপুর বাণিজ্যিক এলাকার নিজস্ব ফ্যাক্টরিতে হয়ে গেল ইউনিটেক প্রডাক্টস (বিডি) লিঃ এর দিনব্যাপী সেলস কনফারেন্স। কনফারেন্সটি অনুষ্ঠিত হয় শনিবার, ১১ই মার্চ, সারা দেশ থেকে প্রায় ৩১০ জন ডিলার এই কনফারেন্সটিতে অংশগ্রহণ করেন এবং ইউনিটেকর ফ্যাক্টরি ঘুরে দেখার সুযোগ পান।এসময় ইউনিটেকর ব্যবস্থাপনা পরিচালক, ইঞ্জি: আনিস আহমেদ ডিলারদের উদ্দেশে বক্তব্য রাখেন এবং ইউনিটেক কে বাংলাদেশের সেরা ইলেক্ট্রনিক ব্র্যান্ড হিসেবে গড়ে তোলার আশ্বাস ব্যক্ত করেন। ইঞ্জি: আনিস আহমেদ, জাতীয় এবং বিভাগীয় পর্যায়ে সেরা ডিলারদের হাতে সার্টিফিকেট, ক্রেস্ট ও প্রাইজ বন্ড তুলে দেন। বিজয়ীরা হলেন রুপালি ইলেক্ট্রনিক্স (জাতীয় সেরা), লিয়া এন্টারপ্রাইজ (দ্বিতীয় জাতীয় সেরা), মদিনা ইলেক্ট্রনিক্স (তৃতীয় জাতীয় সেরা), সুন্দরবন ইলেক্ট্রনিক্স (ঢাকা বিভাগ), আলাউদ্দিন ইলেক্ট্রনিক্স (চিটাগং বিভাগ), শান্ত ইলেক্ট্রনিক্স (রাজশাহী রংপুর বিভাগ), নুরুল এন্টারপ্রাইজ (খুলনা বিভাগ), ফেয়ার ভিউ ইলেক্ট্রনিক্স (বরিশাল বিভাগ) ও ফিডব্যাক কমিউনিকেসন (সিলেট বিভাগ)। কনফারেন্সটিতে আরও বক্তব্য রাখেন ইউনিটেকের বিজনেস ডেভেলপমেন্ট অ্যান্ড প্ল্যানিং ম্যানেজার

Visualize data

In [7]:
print("Total Rows:", len(data))
print("Total Cols:", len(data[19978]))

# for i in range(len(data)):
#   if (len(data[i]) != 2):
#     print(i, data[i], data[i-1], data[i+1])

Total Rows: 19979
Total Cols: 2


In [8]:
a = [1,2,3,5,5,1,4,2,3,5]
print(set(a))

{1, 2, 3, 4, 5}


Show all category

In [ ]:
# count = 0
# for s in data:
#   if(' Science' in s[1]):
#     count += 1
#     print(s[0], s[1])
# print(count)

0


In [9]:
all_categories = set([sample[1] for sample in data])
print(all_categories)
print(len(all_categories))

{'Economy', 'Entertainment', 'Politics', 'International', 'Sports', 'National', 'Science_Technology', 'Education'}
8


test code

Sorting based on category count

In [ ]:
# category_count_list = []
# count = 0
# for cat in all_categories:
#   count = 0
#   for row in data:
#     if row['category'] == cat:
#       count += 1
#   category_count_list.append({'category': cat, 'count': count})
# print(category_count_list)

# from operator import itemgetter
# sorted_cat_count_list = []
# # sorted_cat_count_list = sorted(category_count_list, key=lambda x: x.count, reverse=True)
# category_count_list.sort(key = itemgetter('count'), reverse=True)
# print(category_count_list)

Discard low count catagories

In [ ]:
# selected_cats = []

# for p in category_count_list:
#     if p['count'] > 800:
#         selected_cats.append(p['category'])
# print(selected_cats)
# print(len(selected_cats))

['bangladesh', 'sports', 'international', 'entertainment', 'technology']
5


Prepare data X, Y

In [10]:
x_text = []
y_label = []

for row in data:
  y_label.append(row[1])
  x_text.append(row[0])
print(len(x_text),len(y_label))

19979 19979


Split data into Train & test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_text,y_label, test_size = 0.2, stratify=y_label)

xlm Roberta

In [12]:
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Input, Dense

In [33]:
!pip install tensorflow-hub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
!pip install transformers
import transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.4 MB 28.4 MB/s 
     |████████████████████████████████| 101 kB 12.0 MB/s 
     |████████████████████████████████| 596 kB 49.6 MB/s 
     |████████████████████████████████| 6.6 MB 61.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [14]:
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.2 MB 29.3 MB/s 


In [15]:
from transformers import AutoTokenizer, TFAutoModel, TFXLMRobertaModel

bert_tokenizer = AutoTokenizer.from_pretrained('jplu/tf-xlm-roberta-base')
# bert_model = TFAutoModel.from_pretrained("jplu/tf-xlm-roberta-large")
bert_model = TFXLMRobertaModel.from_pretrained('jplu/tf-xlm-roberta-base')

Downloading:   0%|          | 0.00/512 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/4.83M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.76G [00:00<?, ?B/s]

Some layers from the model checkpoint at jplu/tf-xlm-roberta-base were not used when initializing TFXLMRobertaModel: ['lm_head']
- This IS expected if you are initializing TFXLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFXLMRobertaModel were initialized from the model checkpoint at jplu/tf-xlm-roberta-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLMRobertaModel for predictions without further training.


Tokenize x

In [16]:
# Tokenize the input (takes some time) 
# here tokenizer using from bert-base-cased
x_train = bert_tokenizer(
    text=X_train,
    add_special_tokens=True,
    max_length=512,
    truncation=True,
    padding=True, 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)
x_test = bert_tokenizer(
    text=X_test,
    add_special_tokens=True,
    max_length=512,
    truncation=True,
    padding=True, 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)

In [ ]:
# input_ids = x_train['input_ids']
# attention_mask = x_train['attention_mask']

One hot encoding of Y

In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
def make_ohe(y_label):
  # Label Encode
  encoder = LabelEncoder()
  class_labels = encoder.fit_transform(y_label)
  print(class_labels,len(class_labels),class_labels.shape)
  print(set(class_labels))

  #One hot Encode
  encoder = OneHotEncoder(sparse=False)
  class_labels = class_labels.reshape((class_labels.shape[0], 1))
  y_ohe = encoder.fit_transform(class_labels)
  print(y_ohe,y_ohe.shape)
  return y_ohe

In [18]:
y_train = make_ohe(y_train)
print(type(y_train))

[4 4 3 ... 6 1 3] 15983 (15983,)
{0, 1, 2, 3, 4, 5, 6, 7}
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (15983, 8)
<class 'numpy.ndarray'>


In [19]:
y_test = make_ohe(y_test)
print(type(y_test))

[7 1 2 ... 2 7 5] 3996 (3996,)
{0, 1, 2, 3, 4, 5, 6, 7}
[[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]] (3996, 8)
<class 'numpy.ndarray'>


Building BERT classification model

Create model

In [20]:
max_len = 512
input_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_ids")
input_mask = Input(shape=(max_len,), dtype=tf.int32, name="attention_mask")
embeddings = bert_model(input_ids,attention_mask = input_mask)[0] 
out = tf.keras.layers.GlobalMaxPool1D()(embeddings)
# out = Dense(128, activation='relu')(out)
# out = tf.keras.layers.Dropout(0.1)(out)
out = Dense(32,activation = 'relu')(out)
y = Dense(8,activation = 'softmax')(out)
model = tf.keras.Model(inputs=[input_ids, input_mask], outputs=y)
model.layers[2].trainable = True
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 tfxlm_roberta_model (TFXLMRobe  TFBaseModelOutputWi  278043648  ['input_ids[0][0]',              
 rtaModel)                      thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 512,                                           

Compile model

In [21]:
optimizer = Adam(
    learning_rate=5e-05, # this learning rate is for bert model , taken from huggingface website 
    epsilon=1e-08,
    decay=0.01,
    clipnorm=1.0)
# Set loss and metrics
# loss =CategoricalCrossentropy(from_logits = True)
# metrics = CategoricalAccuracy('balanced_accuracy'),
loss='categorical_crossentropy'
metrics=['accuracy']
# Compile the model
model.compile(
    optimizer = optimizer,
    loss = loss, 
    metrics = metrics)

Train model

In [22]:
train_history = model.fit(x ={'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']},y= y_train, epochs=3, batch_size = 6)

Epoch 1/3
2664/2664 [==============================] - 2307s 858ms/step - loss: 0.4745 - accuracy: 0.8578
Epoch 2/3
2664/2664 [==============================] - 2293s 861ms/step - loss: 0.2607 - accuracy: 0.9255
Epoch 3/3
2664/2664 [==============================] - 2293s 861ms/step - loss: 0.2291 - accuracy: 0.9347


In [37]:
train_history = model.fit(x ={'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']},y= y_train, epochs=3, batch_size = 6)

Epoch 1/3
2664/2664 [==============================] - 2283s 857ms/step - loss: 0.2095 - accuracy: 0.9408
Epoch 2/3
2664/2664 [==============================] - 2293s 861ms/step - loss: 0.1995 - accuracy: 0.9441
Epoch 3/3
2664/2664 [==============================] - 2293s 861ms/step - loss: 0.1912 - accuracy: 0.9458


In [47]:
train_history = model.fit(x ={'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']},y= y_train, epochs=1, batch_size = 6)

2664/2664 [==============================] - 2295s 862ms/step - loss: 0.1859 - accuracy: 0.9480


In [48]:
model.save("xlmRoberta_20k.h5")

In [ ]:
saved_model = tf.keras.models.load_model("xlmRoberta_20k.h5",custom_objects={'KerasLayer':hub.KerasLayer})

In [27]:
from sklearn.metrics import classification_report

Train accuracy

In [49]:
predicted_raw_train = model.predict({'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']})
predicted_raw_train[0]

array([2.3434128e-01, 6.4161333e-04, 5.8825109e-03, 6.6229078e-04,
       7.5298542e-01, 2.0120227e-04, 5.2639162e-03, 2.1731834e-05],
      dtype=float32)

In [28]:
y_predicted_train = np.argmax(predicted_raw_train, axis = 1)
y_true_train = np.argmax(y_train, axis = 1)
print(classification_report(y_true_train, y_predicted_train))

              precision    recall  f1-score   support

           0       0.89      0.92      0.91      2000
           1       0.95      0.95      0.95      2000
           2       0.97      0.98      0.97      2000
           3       0.94      0.94      0.94      2000
           4       0.85      0.90      0.87      2000
           5       1.00      0.90      0.95      2000
           6       0.94      0.92      0.93      1983
           7       0.98      0.99      0.98      2000

    accuracy                           0.94     15983
   macro avg       0.94      0.94      0.94     15983
weighted avg       0.94      0.94      0.94     15983



In [40]:
y_predicted_train = np.argmax(predicted_raw_train, axis = 1)
y_true_train = np.argmax(y_train, axis = 1)
print(classification_report(y_true_train, y_predicted_train))

              precision    recall  f1-score   support

           0       0.92      0.93      0.92      2000
           1       0.95      0.96      0.96      2000
           2       0.98      0.98      0.98      2000
           3       0.95      0.96      0.96      2000
           4       0.85      0.91      0.88      2000
           5       1.00      0.90      0.95      2000
           6       0.95      0.94      0.95      1983
           7       0.98      0.99      0.99      2000

    accuracy                           0.95     15983
   macro avg       0.95      0.95      0.95     15983
weighted avg       0.95      0.95      0.95     15983



In [50]:
y_predicted_train = np.argmax(predicted_raw_train, axis = 1)
y_true_train = np.argmax(y_train, axis = 1)
print(classification_report(y_true_train, y_predicted_train))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92      2000
           1       0.95      0.96      0.96      2000
           2       0.98      0.98      0.98      2000
           3       0.96      0.95      0.96      2000
           4       0.88      0.90      0.89      2000
           5       1.00      0.92      0.96      2000
           6       0.95      0.95      0.95      1983
           7       0.98      0.99      0.99      2000

    accuracy                           0.95     15983
   macro avg       0.95      0.95      0.95     15983
weighted avg       0.95      0.95      0.95     15983



Test accuracy

In [51]:
predicted_raw = model.predict({'input_ids':x_test['input_ids'],'attention_mask':x_test['attention_mask']})
predicted_raw[0]

array([1.7128641e-03, 1.7225569e-03, 3.1797241e-03, 9.7505451e-04,
       2.2094592e-04, 2.2434026e-03, 3.6544143e-04, 9.8957998e-01],
      dtype=float32)

In [30]:
y_predicted = np.argmax(predicted_raw, axis = 1)
y_true = np.argmax(y_test, axis = 1)
print(classification_report(y_true, y_predicted))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       500
           1       0.91      0.92      0.91       500
           2       0.95      0.97      0.96       500
           3       0.92      0.90      0.91       500
           4       0.82      0.84      0.83       500
           5       0.99      0.88      0.93       500
           6       0.89      0.89      0.89       496
           7       0.96      0.98      0.97       500

    accuracy                           0.91      3996
   macro avg       0.91      0.91      0.91      3996
weighted avg       0.91      0.91      0.91      3996



In [42]:
y_predicted = np.argmax(predicted_raw, axis = 1)
y_true = np.argmax(y_test, axis = 1)
print(classification_report(y_true, y_predicted))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       500
           1       0.91      0.92      0.92       500
           2       0.95      0.96      0.95       500
           3       0.92      0.91      0.91       500
           4       0.82      0.85      0.84       500
           5       0.99      0.88      0.93       500
           6       0.89      0.91      0.90       496
           7       0.97      0.98      0.98       500

    accuracy                           0.91      3996
   macro avg       0.91      0.91      0.91      3996
weighted avg       0.91      0.91      0.91      3996



In [52]:
y_predicted = np.argmax(predicted_raw, axis = 1)
y_true = np.argmax(y_test, axis = 1)
print(classification_report(y_true, y_predicted))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86       500
           1       0.91      0.92      0.92       500
           2       0.95      0.96      0.95       500
           3       0.93      0.89      0.91       500
           4       0.85      0.84      0.84       500
           5       0.99      0.91      0.95       500
           6       0.88      0.91      0.90       496
           7       0.97      0.98      0.98       500

    accuracy                           0.91      3996
   macro avg       0.91      0.91      0.91      3996
weighted avg       0.91      0.91      0.91      3996



Done for now!

In [43]:
from tensorflow import keras
model = keras.models.load_model('xlmRoberta_20k.h5')

ValueError: ignored

In [36]:
!python3 -c "import tensorflow as tf; print(tf.__version__)"


2.8.2


In [46]:
import tensorflow_hub as hub
saved_model = tf.keras.models.load_model("xlmRoberta_20k.h5",custom_objects={'KerasLayer':hub.KerasLayer})

ValueError: ignored

In [ ]:
train_history = saved_model.fit(x ={'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']},y= y_train, epochs=3, batch_size = 6)

Test for any string

In [ ]:
texts = input(str('input the text'))
x_val = tokenizer(
    text=texts,
    add_special_tokens=True,
    max_length=70,
    truncation=True,
    padding='max_length', 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True) 
validation = model.predict({'input_ids':x_val['input_ids'],'attention_mask':x_val['attention_mask']})*100
for key , value in zip(encoded_dict.keys(),validation[0]):
    print(key,value)

Done

Save model

In [ ]:
# model = tf.keras.models.load_model("mbert_80k.h5")
saved_model = tf.keras.models.load_model("mbert_80k.h5",custom_objects={'KerasLayer':hub.KerasLayer})

Train data accuracy evaluation

In [ ]:
y_predicted_train = model.predict(X_train)
y_out_train = []
y_out_pred_train = []
true_count = 0
for i in range(len(y_predicted_train)):
  y_out_train.append(np.argmax(y_train[i]))
  y_out_pred_train.append(np.argmax(y_predicted_train[i]))
  if (y_out_train[i] == y_out_pred_train[i]):
    true_count += 1
# print(np.shape(y_out),np.shape(y_label))

accuracy = true_count/len(y_train)
print(accuracy)
# print(y_out)

0.6740204880885194


Test data accuracy evaluation

In [ ]:
y_predicted = model.predict(X_test)
y_out = []
y_out_pred = []
true_count = 0
for i in range(len(y_predicted)):
  y_out.append(np.argmax(y_test[i]))
  y_out_pred.append(np.argmax(y_predicted[i]))
  if (y_out[i] == y_out_pred[i]):
    true_count += 1
print(np.shape(y_out),np.shape(y_label))

accuracy = true_count/len(y_test)
print(accuracy)
# print(y_out)